routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CKEditorController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NosotroController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProyectoController;
use App\Http\Controllers\ServicioController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [PagesController::class, 'index'])->name('index');
Route::get('/nosotros', [PagesController::class, 'nosotros'])->name('nosotros');
Route::get('/servicios', [PagesController::class, 'servicios'])->name('servicios');
Route::get('/servicio/{id}', [PagesController::class, 'serviciosView'])->name('servicioView');

Route::get('/proyectos', [PagesController::class, 'proyectos'])->name('proyectos');
Route::get('/proyecto/{id}', [PagesController::class, 'proyectoView'])->name('proyectoView');
Route::get('/blog', [PagesController::class, 'blog'])->name('blog');
Route::get('/blog/{id}', [PagesController::class, 'blogView'])->name('blogView');

Route::get('/clientes', [PagesController::class, 'clientes'])->name('clientes');

Route::get('/contacto', function () {
    return view('contacto');
});
Route::get('/table', function () {
    return view('table');
});
Route::post('contactStore', [PagesController::class, 'contactStore'])->name('contactStore');
Route::post('ckeditor/image_upload', [CKEditorController::class, 'upload'])->name('upload');

Route::get('/clear', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    Artisan::call('config:clear');
    Artisan::call('view:clear');
    Artisan::call('key:generate');
    Artisan::call('storage:link');
    return "Cleared!";
});

Route::get('/migrateUpdate', function () {
    Artisan::call('migrate --path=database/migrations --seed');
    return "Cleared!";
});


Auth::routes(['register' => false]);
Route::get('logout',[LoginController::class, 'logout'])->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/administracion', [AdminController::class, 'index'])->name('admin');
    Route::resource('admin-nosotros', NosotroController::class);
    Route::resource('admin-servicios', ServicioController::class);
    Route::resource('admin-clientes', ClienteController::class);
    Route::resource('admin-proyectos', ProyectoController::class);
    Route::resource('admin-blog', BlogController::class);
    Route::resource('admin-home', HomeController::class);
});

app/Models/Servicio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Servicio extends Model
{
    use HasFactory;
}

app/Http/Controllers/ServicioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Servicio;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ServicioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $servicios = Servicio::get();
        return view('admin.servicios.index')->with('servicios',$servicios);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.servicios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $name = $request->hasFile('img') ? Storage::disk('public')->put('home',  $request->file('img')) :  $request->img_act;

        if($request->hasFile('img')){
            $name =  Storage::disk('public')->put('servicios',  $request->file('img'));
        }else{
            return redirect()->back()->with('error', 'La imagen es requerida para crear el servicio'); 
        }

        $servicio =  new Servicio();
        $servicio->titulo = $request->titulo;
        $servicio->descripcion = $request->descripcion;
        $servicio->img = $name;
        $servicio->save();

        return redirect()->back()->with('success', 'Se ha creado correctamente'); 

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Servicio  $servicio
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Servicio  $servicio
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $servicio = Servicio::find($id);
        return view('admin.servicios.edit')->with('servicio',$servicio);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Servicio  $servicio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $name = $request->hasFile('img') ? Storage::disk('public')->put('servicios',  $request->file('img')) :  $request->img_act;
        $servicio = Servicio::find($id);
        $servicio->titulo = $request->titulo;
        $servicio->descripcion = $request->descripcion;
        $servicio->img = $name;
        $servicio->save();
        return redirect()->back()->with('success', 'Se ha actualizado correctamente'); 

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Servicio  $servicio
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $servicio = Servicio::find($id)->delete();
        return redirect()->back()->with('success', 'Se ha eliminado correctamente'); 
    }
}

resources/views/admin/servicios/create.blade.php
@extends('admin.layouts.app')
@section('css')
<link href="{{asset('admin/plugins/file-upload/file-upload-with-preview.min.css')}}" rel="stylesheet" type="text/css" />   
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
@endsection
@section('content')

    @include('admin.layouts.sidebarDesk')
      <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">
                <div class="page-header">
                    <div class="page-title">
                        <h3>Administrador -  Crear Servicios</h3>
                    </div>
                </div>

                <div class="row layout-top-spacing">
                  
                    <div class="col-lg-12">
                        <div class="widget-content widget-content-area br-6">
                            @if (\Session::has('success'))
                                <div class="row">
                                    <div class="col-12">
                                        <div class="alert alert-success" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><svg> ... </svg></button>
                                            <strong> {!! \Session::get('success') !!} </strong> 
                                        </div>
                                    </div>
                                </div>
                            @endif

                            @if (\Session::has('error'))
                                <div class="row">
                                    <div class="col-12">
                                        <div class="alert alert-danger" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><svg> ... </svg></button>
                                            <strong>{!! \Session::get('error') !!} </strong> 
                                        </div>
                                    </div>
                                </div>
                            @endif
                            
                            
                            <form action=" {{route('admin-servicios.store')}} "  method="POST" enctype="multipart/form-data">

                                @csrf
                                <div class="row">
                                    <div class="form-group mb-4 col-12">
                                        <label for="formGroupExampleInput">Titulo del Servicio</label>
                                        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="" name="titulo">
                                    </div>
                                    <div class="form-group col-12">
                                        <label for="exampleFormControlTextarea1">Descripcion del servicio</label>
                                        <textarea class="form-control"  rows="3" id="quienes" name="descripcion"> @if(isset($home)) {{$home->text}} @endif </textarea>
                                        <script>
                                            CKEDITOR.replace( 'quienes' );
                                        </script>
                                    </div>
                                    <div class="custom-file-container col-12" data-upload-id="myQuienes">
                                        <label>Imagen <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">x</a></label>
                                        <label class="custom-file-container__custom-file" >
                                            <input type="file" class="custom-file-container__custom-file__custom-file-input" accept="image/*" name="img">
                                            <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
                                            <span class="custom-file-container__custom-file__custom-file-control"></span>
                                        </label>
                                        <div class="custom-file-container__image-preview"></div>
                                    </div>
                                    <button class="btn btn-outline-primary btn-block">Guardar</button>
                                </div>
                                
                            </form>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    

@endsection
@section('script')
  
     <!-- BEGIN PAGE LEVEL PLUGINS -->
     <script src="{{asset('admin/assets/js/scrollspyNav.js')}}"></script>
     <script src="{{asset('admin/plugins/file-upload/file-upload-with-preview.min.js')}}"></script>
 
     <script>
         //First upload
         var firstUpload = new FileUploadWithPreview('myQuienes')

     </script>
     <!-- END PAGE LEVEL PLUGINS -->   
@endsection

resources/views/admin/servicios/edit.blade.php
@extends('admin.layouts.app')
@section('css')
<link href="{{asset('admin/plugins/file-upload/file-upload-with-preview.min.css')}}" rel="stylesheet" type="text/css" />   
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
@endsection
@section('content')

    @include('admin.layouts.sidebarDesk')
      <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">
                <div class="page-header">
                    <div class="page-title">
                        <h3>Administrador -  Editar Servicios</h3>
                    </div>
                </div>

                <div class="row layout-top-spacing">
                  
                    <div class="col-lg-12">
                        <div class="widget-content widget-content-area br-6">
                            @if (\Session::has('success'))
                                <div class="row">
                                    <div class="col-12">
                                        <div class="alert alert-success" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><svg> ... </svg></button>
                                            <strong> {!! \Session::get('success') !!} </strong> 
                                        </div>
                                    </div>
                                </div>
                            @endif

                            @if (\Session::has('error'))
                                <div class="row">
                                    <div class="col-12">
                                        <div class="alert alert-danger" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><svg> ... </svg></button>
                                            <strong>{!! \Session::get('error') !!} </strong> 
                                        </div>
                                    </div>
                                </div>
                            @endif
                            
                            
                            <form action="{{route('admin-servicios.update', $servicio->id)}}"  method="POST" enctype="multipart/form-data">

                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="form-group mb-4 col-12">
                                        <label for="formGroupExampleInput">Titulo del Servicio</label>
                                        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="" name="titulo" value="{{$servicio->titulo}}">
                                    </div>
                                    <div class="form-group col-12">
                                        <label for="exampleFormControlTextarea1">Descripcion del servicio</label>
                                        <textarea class="form-control"  rows="3" id="quienes" name="descripcion">{{$servicio->descripcion}}  </textarea>
                                        <script>
                                            CKEDITOR.replace( 'quienes' );
                                        </script>
                                    </div>

                                    @if(isset($servicio))
                                    <div class="col-12 text-center m-2">
                                        <p>Imagen Actual</p> 
                                        <img src="{{asset(env('STORAGE_LINK'))}}/{{$servicio->img}}" alt="imagen" width="400">
                                    </div>
                                    <input type="hidden" name="img_act" value="{{$servicio->img}}">
                                    @endif

                                    <div class="custom-file-container col-12" data-upload-id="myQuienes">
                                        <label>Imagen <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">x</a></label>
                                        <label class="custom-file-container__custom-file" >
                                            <input type="file" class="custom-file-container__custom-file__custom-file-input" accept="image/*" name="img">
                                            <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
                                            <span class="custom-file-container__custom-file__custom-file-control"></span>
                                        </label>
                                        <div class="custom-file-container__image-preview"></div>
                                    </div>
                                    <button class="btn btn-outline-primary btn-block">Guardar</button>
                                </div>
                                
                            </form>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    

@endsection
@section('script')
  
     <!-- BEGIN PAGE LEVEL PLUGINS -->
     <script src="{{asset('admin/assets/js/scrollspyNav.js')}}"></script>
     <script src="{{asset('admin/plugins/file-upload/file-upload-with-preview.min.js')}}"></script>
 
     <script>
         //First upload
         var firstUpload = new FileUploadWithPreview('myQuienes')

     </script>
     <!-- END PAGE LEVEL PLUGINS -->   
@endsection

resources/views/admin/servicios/index.blade.php
@extends('admin.layouts.app')
@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('admin/plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin/plugins/table/datatable/dt-global_style.css')}}">
@endsection
@section('content')

    @include('admin.layouts.sidebarDesk')
      <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">
                <div class="page-header">
                    <div class="page-title">
                        <h3>Administrador - Servicios</h3>
                    </div>
                </div>

                <div class="row layout-top-spacing">
                    <div class="col-lg-12">
                        <div class="widget-content widget-content-area br-6">

                            <div class="row ">
                                <div class="col-12">
                                    <a href="admin-servicios/create" class="btn btn-primary"> Crear Servicio</a>
                                </div>
                            </div>

                            <div class="table-responsive mb-4 mt-4">
                                <table id="zero-config" class="table table-hover" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th class="text-center">Titulo</th>
                                            <th class="text-center">Imagen</th>
                                            <th class="no-content text-center">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($servicios as $item)
                                        <tr>
                                            <td class="text-center"> {{$item->titulo}}</td>
                                            <td class="text-center"> <img src="{{asset(env('STORAGE_LINK'))}}/{{$item->img}}" alt="imagen" width="80">
                                            </td>
                                            <td class="text-center">
                                                <div class="btn-group" role="group" aria-label="Basic example">
                                                    <a type="button" href="{{route('admin-servicios.edit',$item->id)}}" class="btn btn-secondary">Editar</a>
                                                    <form action="{{ route('admin-servicios.destroy',$item->id)}}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                        <button type="submit" class="btn btn-secondary">Eliminar</button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                        @endforeach
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    

@endsection
@section('script')

     <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{asset('admin/plugins/table/datatable/datatables.js')}}"></script>
    <script>
        $('#zero-config').DataTable({
            "oLanguage": {
                "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
                "sInfo": "Showing page _PAGE_ of _PAGES_",
                "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                "sSearchPlaceholder": "Search...",
               "sLengthMenu": "Results :  _MENU_",
            },
            "stripeClasses": [],
            "lengthMenu": [10, 20, 50],
            "pageLength": 10
        });
    </script>
     <!-- END PAGE LEVEL PLUGINS -->   
@endsection